# Generated by Django 5.2.5 on 2025-10-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentattempt_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='stripe_payment_id',
            new_name='stripe_refund_id',
        ),
    ]
