# Generated by Django 5.2.5 on 2025-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentAttemt',
            new_name='PaymentAttempt',
        ),
    ]
