# Generated by Django 5.2.5 on 2025-10-05 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_paymentattemt_paymentattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Attempt', 'verbose_name_plural': 'Payment Attempts'},
        ),
        migrations.RemoveField(
            model_name='refund',
            name='stripe_refund_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='paymentattempt',
            table='payment_attempts',
        ),
    ]
